assetic:
    bundle: [ LugosiumOVHVPSMonitorBundle ]
    assets:
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]
        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        jquery_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
                - bundles/lugosiumovhvpsmonitor/js/chosen/chosen.jquery.min.js
        highcharts_js:
            inputs:
                - bundles/lugosiumovhvpsmonitor/js/highcharts/highcharts.js
                - bundles/lugosiumovhvpsmonitor/js/highcharts/modules/exporting.js
        chosen_css:
            inputs:
                - bundles/lugosiumovhvpsmonitor/js/chosen/chosen.min.css
        dashboard_js:
            inputs:
                - bundles/lugosiumovhvpsmonitor/js/Dashboard.js
                - bundles/lugosiumovhvpsmonitor/js/Dashboard/Memory.js
                - bundles/lugosiumovhvpsmonitor/js/Dashboard/Cpu.js
                - bundles/lugosiumovhvpsmonitor/js/Dashboard/Network.js

